AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '[]'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Metrics/MethodLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
