---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - test/support/dummy.rb
    - vendor/**/*

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
